<?php
// Start the session to access the stored data
session_start();

// Include TCPDF library
require_once('../TCPDF/TCPDF-main/tcpdf.php');

// Establish a new database connection
$conn = new mysqli("127.0.0.1", "root", "", "employeecollection");

// Check the connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}


// Define a custom TCPDF class
class MyPDF extends TCPDF {
    // Page footer
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);

        // Set font
        $this->SetFont('helvetica', 'I', 8);

        // Set steel gray color for the copyright cell
        $this->SetFillColor(220, 220, 220);
        $this->Cell(0, 10, '© 2024 Lorem Ipsum Loaning Company. All rights reserved.', 0, 0, 'L', 1);

        // Set white color for the cell with page number
        $this->SetFillColor(255, 255, 255);
        $this->Cell(0, 10, 'Page ' . $this->getAliasNumPage(), 0, 0, 'R', 1);
    }
}


// Check if the session data is set
if (isset($_SESSION['viewstatement_data'])) {
    // Retrieve the data from the session
    $data = $_SESSION['viewstatement_data'];

    // Create a new PDF instance
    $pdf = new MyPDF();

    // Set page margins
    $pdf->SetMargins(10, 10, 10); // You can adjust these values as needed
    // Set page orientation to landscape
    $pdf->SetPageOrientation('P');
    // Add a page
    $pdf->AddPage();
// Calculate the available width for the logo based on page width and margins
    $availableWidth = $pdf->getPageWidth() - $pdf->getMargins()['left'] - $pdf->getMargins()['right'];

    $pdf->ln(4);
    // Set the logo width to fit the available width
    $logoWidth = $availableWidth;

    // Add header logo
    $logoPath = 'images/LOGO_RemoveBG.jpg"';  // Specify the path to your logo file
    $pdf->Image($logoPath, 10, 10, $logoWidth);

    $pdf->ln(30);

    //header

    $pdf->SetFillColor(169,169,169);
    $pdf->SetTextColor(245,245,245);
    $pdf->SetFont('dejavuserif', 'B', 19);

    $pdf->Cell( $logoWidth, 15, "TAX INVOICE", 1, 1, 'C', 1); 
    $pdf->ln(5);


    //reset fonts
    $pdf->SetFont('helvetica', '', 10);
    $pdf->SetTextColor(0,0,0);

    date_default_timezone_set('Asia/Kolkata');

      
    if (isset($data) && is_array($data) && count($data) > 0) {
        
        $userId = $data[0]['s_User_ID'];
        $username = $data[0]['s_Username'];
        $currentDateTime = date('Y-m-d H:i:s');
                // Set dark blue color for the cells with white and bold font
                $pdf->SetFillColor(84,109,133); // Dark blue (RGB: 0, 0, 128)
                $pdf->SetTextColor(255, 255, 255); // White font color
                $pdf->SetFont('helvetica', 'B', 9);

                // User ID
                $pdf->Cell($availableWidth/5, 9, "    User ID", 0, 0, 'L', 1); 

                $pdf->SetFillColor(84,109,133);
                $pdf->SetTextColor(255, 255, 255);


                $pdf->Cell($availableWidth/5, 9, ":      $userId", 0, 0, 'L', 1);

                $pdf->SetFillColor(255, 255, 255);
                $pdf->Cell($availableWidth/5, 9, "", 0, 0, 'L', 1);

                $pdf->SetFillColor(84,109,133);
                $pdf->SetTextColor(255, 255, 255);
         

                $pdf->Cell($availableWidth/2.5, 9, "      Report generated by  :  Admin", 0, 1, 'L', 1);


                $pdf->SetFillColor(84,109,133);
                $pdf->SetTextColor(255, 255, 255);
                $pdf->SetFont('helvetica', 'B', 9);

                // Username
                $pdf->Cell($availableWidth/5, 9, "    Username", 0, 0, 'L', 1);

                $pdf->SetFillColor(84,109,133);
                $pdf->SetTextColor(255, 255, 255);
           

                $pdf->Cell($availableWidth/5, 9, ":      $username", 0, 0, 'L', 1);

                $pdf->SetFillColor(255, 255, 255);
                $pdf->Cell($logoWidth/5, 9, "", 0, 0, 'L', 1);

                $pdf->SetFillColor(84,109,133);
                $pdf->SetTextColor(255, 255, 255);
              

                $pdf->Cell($availableWidth/5, 9, "      Report generated at", 0, 0, 'L', 1);

                $pdf->SetFillColor(84,109,133);
                $pdf->SetTextColor(255, 255, 255);
         
                $pdf->Cell($availableWidth/5, 9, " :  $currentDateTime", 0, 0, 'L', 1);

                // Reset font and colors for the rest of the document
                $pdf->SetFont('helvetica', '', 10);
                $pdf->SetTextColor(0, 0, 0);
                $pdf->SetFillColor(255, 255, 255);


    } else {

        echo "Error: Invalid or empty data.";
    }

    $pdf->Ln(18);

    // Add table header
        $pdf->SetFillColor(169,169,169);
    $pdf->Cell($availableWidth * 0.075, 20, 'User ID', 1, 0, 'C', 1);
    $pdf->Cell($availableWidth * 0.1, 20, 'Username', 1, 0, 'C', 1);
    $pdf->Cell($availableWidth * 0.15, 20, 'Total Amount', 1, 0, 'C', 1);
    $pdf->Cell($availableWidth * 0.16, 20, 'Balance Amount', 1, 0, 'C', 1);
    $pdf->Cell($availableWidth * 0.15, 20, 'Amount Paid', 1, 0, 'C', 1);
    $pdf->Cell($availableWidth * 0.12, 20, 'Date', 1, 0, 'C', 1);
    $pdf->Cell($availableWidth * 0.13, 20, 'Time', 1, 0, 'C', 1);
    $pdf->Cell($availableWidth * 0.12, 20, 'Action', 1, 1, 'C', 1);  // Move to the next line


    $pdf->SetFont('helvetica', '', 10);

    $tot_rem=0;
    $pending=0;
    $tot_amnt=0;

    $fill = false;

    // Iterate over the data and add rows to the PDF
    foreach ($data as $row) {

        $pdf->SetFillColor($fill ? 255 : 240, $fill ? 255 : 240, $fill ? 255 : 240);

        $pdf->Cell($availableWidth * 0.075, 10, $row['s_User_ID'], 1, 0, 'C');
        $pdf->Cell($availableWidth * 0.1, 10, $row['s_Username'], 1, 0, 'C');
        $pdf->Cell($availableWidth * 0.15, 10, $row['s_Total_Amount'], 1, 0, 'C');
        $pdf->Cell($availableWidth * 0.16, 10, $row['s_Remaining_Amount'], 1, 0, 'C');
        $pdf->Cell($availableWidth * 0.15, 10, $row['s_amount_credited'], 1, 0, 'C');
        $pdf->Cell($availableWidth * 0.12, 10, $row['s_date'], 1, 0, 'C');
        $pdf->Cell($availableWidth * 0.13, 10, $row['s_time'], 1, 0, 'C');
        $pdf->Cell($availableWidth * 0.12, 10, $row['s_action'], 1, 1, 'C');
        
        
        $tot_rem+= $row['s_amount_credited'];
        $pending=$row['s_Remaining_Amount'];
        $tot_amnt=$row['s_Total_Amount'];  
        
        $fill = !$fill;
   
    }

  

    $pdf->ln(2);

    $pdf->SetFont('helvetica', 'b', 10);
    $pdf->Cell($logoWidth, 10, " Amount paid totally = $tot_rem", 0, 1, 'R'); 
    $pdf->Cell($logoWidth, 10, " Amount Pending = $pending", 0, 1, 'R');
    $pdf->Cell($logoWidth, 10, " __________________________", 0, 1, 'R');
    $pdf->Cell($logoWidth, 10, " Total Amount = $tot_amnt", 0, 1, 'R');

     

    // Output the PDF as inline
    $pdf->Output('Output.pdf', 'I');

    // Unset the session data to avoid using it again
    unset($_SESSION['viewstatement_data']);
} else {
    // Handle the case where session data is not set
    echo "Error: Session data not found.";
}

// Close the database connection
$conn->close();
